services:
  app:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
      target: Dev
    container_name: ${PROJECT_PREFIX}
    hostname: ${PROJECT_PREFIX}
    ports:
      - "${WEB_PORT}:8080"
    volumes:
      - ./code:/var/www/html
      - .:/app
      - vendor_volume:/app/code/vendor
      - cache_volume:/app/code/storage/framework/cache
      - view_cache_volume:/app/code/storage/framework/views
      - vendor_volume:/var/www/html/vendor
      - cache_volume:/var/www/html/storage/framework/cache
      - view_cache_volume:/var/www/html/storage/framework/views
      - postgres_data:/var/lib/postgresql/14/main
      - ./docker/web/init.sh:/init.sh
      - ./docker/web/supervisord/supervisord-dev.conf:/etc/supervisor/conf.d/supervisord.conf
      - ./docker/web/nginx/default-dev.conf:/etc/nginx/conf.d/default.conf
    working_dir: /app/code
    env_file:
      - .env
    command: bash /init.sh & tail -f /var/log/supervisor/supervisord.log
  prod:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    container_name: ${PROJECT_PREFIX}-prod
    hostname: ${PROJECT_PREFIX}-prod
    volumes:
      - ./docker/web/supervisord/supervisord-dev.conf:/etc/supervisor/conf.d/supervisord.conf
      - vendor_volume_prd:/var/www/html/vendor
      - cache_volume_prd:/var/www/html/storage/framework/cache
      - view_cache_volume_prd:/var/www/html/storage/framework/views
      - postgres_data_prd:/var/lib/postgresql/14/main
    ports:
      - "${WEB_PORT_PRD}:8080"
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
    env_file:
      - .env
  pgadmin:
    image: dpage/pgadmin4
    container_name: ${PROJECT_PREFIX}-pgadmin
    ports:
      - "${PG_ADMIN}:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    depends_on:
      - app
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  pgadmin_data:
  postgres_data:
  vendor_volume:
  cache_volume:
  view_cache_volume:
  postgres_data_prd:
  vendor_volume_prd:
  cache_volume_prd:
  view_cache_volume_prd:
